sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8

env:
  global:
    - DOCKER_CFG=$HOME/.docker
    - DOCKER_REPO="utplsqlv3/oracledb"
    - CACHE_DIR=$HOME/.cache
    - MAVEN_HOME=/usr/local/maven
    - MAVEN_CFG=$HOME/.m2
    - DB_URL="127.0.0.1:1521:XE"
    - DB_USER=app
    - DB_PASS=app
    - ORACLE_VERSION="11g-r2-xe"
    - DOCKER_OPTIONS="--shm-size=1g"
    - UTPLSQL_FILE="utPLSQL"
  matrix:
    - UTPLSQL_VERSION="v3.0.0"
      UTPLSQL_FILE="utPLSQLv3.0.0"
    - UTPLSQL_VERSION="v3.0.1"
    - UTPLSQL_VERSION="v3.0.2"
    - UTPLSQL_VERSION="v3.0.3"
    - UTPLSQL_VERSION="v3.0.4"
    - UTPLSQL_VERSION="v3.1.0"
    - UTPLSQL_VERSION="v3.1.1"
    - UTPLSQL_VERSION="develop"
      UTPLSQL_FILE="utPLSQL"

cache:
  directories:
    - $DOCKER_CFG
    - $CACHE_DIR
    - $MAVEN_CFG

install:
  - bash .travis/maven_cfg.sh
  - bash .travis/start_db.sh
  - bash .travis/install_utplsql.sh
  - bash .travis/install_demo_project.sh

before_script:
  - cp .travis/settings.xml $MAVEN_CFG/settings.xml

script:
  - mvn verify -B

before_deploy:
  - if [ ! -z "$TRAVIS_TAG" ]; then VERSION=$(tr -d "/v/" <<<$TRAVIS_TAG); mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=${VERSION}; fi

deploy:
  - provider: script
    script: mvn clean deploy -DskipTests=true -B -U
    skip_cleanup: true
    on:
      repository: utPLSQL/utPLSQL-java-api
      tags: true
      # Use only first job "#xxx.1" to publish artifacts
      condition: "${TRAVIS_JOB_NUMBER} =~ \\.1$"

  - provider: script
    script: mvn clean deploy -DskipTests=true -B -U
    skip_cleanup: true
    on:
      repository: utPLSQL/utPLSQL-java-api
      branch: develop
      # Use only first job "#xxx.1" to publish artifacts
      condition: "${TRAVIS_JOB_NUMBER} =~ \\.1$"

notifications:
  slack:
    rooms:
      - secure: "RTwZxg50LgiDo8/Z0ZGrYP7+gHFXlDjcAlXu7IGne8/O/79B8UVG3KP5j4PHuRtlt86WBflXB/5nhszgwjleEhNVdciuBPTBv3PHtvoYnqEajtoDsBR4fiqpGk4QJREqYo5UwzBVisEtGS2qvhjOVRy5sgfPqdXfKM4Jl6x6EMoPmuEWKPZW80eO1AXD2lhcT35fxKAuEavKDrY9WKB3P8HycySFm2+IOgEvxk7p3qkukd/AMOPW54A52ry5AkwElj7439DV8MGYOHnrK9f5neMGCi6Q8VzUlTf95WbF7yoPWHNOMPt0LFKtnDOEjljwrRDpf8D/TcbLO5Q03kgOcXOB/KJp8WqgViGT8WO963GPBM7JXD4f5h04QYVn9lab8M6nK1PQZVKuzq6qBcjGW06EmczaseKnc5VW0tc/svw0Qhgot1rh3bRMHe9xX1j2wgfNcqeHFkoRX2AtPBtH5tDsWYVY0148wJ3cLXKZf1hxRd7V6gFfE5fVey/rTRVk8eEpNEhudIZCJ/T/ng3DWC271uPne7B/E2jy3jrgQ5p+VfcjC8dSu65Gmu7hWEON8g2cD8YQxCEryqgaCRn5R77FHWi9Gi3a85Kh951qL6mLxMl44VFil4CGdGi0hJpWPaGvSNNbfXx5eNyzHwjjT5fgk0EDOWVyHaO/Ni6jDFM="
    on_success: change
    on_failure: always
